version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.1
  rebase-strategy: disabled
