redis:
        image: redis:3
        ports:
                - "6379:6379"

ingester:
        image: docker.lcogt.net/ingester:latest
        links:
                - redis
        environment:
                BROKER_URL: redis://redis
