[tool.poetry]
name = "ocs-ingester"
version = "3.2.0"
description = "Ingest frames into the science archive of an observatory control system"
authors = ["Observatory Control System Project <ocs@lco.global>"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://observatorycontrolsystem.github.io"
repository = "https://github.com/observatorycontrolsystem/ingester"
keywords = [
    "observations",
    "astronomy",
    "astrophysics",
    "cosmology",
    "science",
    "archive"
]
classifiers=[
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Physics"
]

[tool.poetry.dependencies]
python = ">=3.11"
boto3 = ">=1,<2"
requests = ">=2,<3"
python-dateutil = ">=2,<3"
astropy = ">=7,<9.0"
numpy = "^2"
ocs_archive = { git = "https://github.com/observatorycontrolsystem/ocs_archive.git", branch = "fix/reduction_level_parsing" }
lcogt-logging = "<1.0.0"
opentsdb-python-metrics = ">=0.2.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=7,<8"

[tool.poetry.group.CI.dependencies]
coveralls = ">=3,<4"

[tool.poetry.scripts]
ocs_ingest_frame = "ocs_ingester.scripts.ingest_frame:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
